---
abstract: 'Dynamic/Nested Workflows that can act as methods on an object.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Fennec::Lite: 0.004
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Method-Workflow
provides:
  Method::Workflow:
    file: lib/Method/Workflow.pm
    version: 0.204
  Method::Workflow::Method:
    file: lib/Method/Workflow/Method.pm
  Method::Workflow::Result:
    file: lib/Method/Workflow/Result.pm
  Method::Workflow::SubClass:
    file: lib/Method/Workflow/SubClass.pm
  Method::Workflow::Task:
    file: lib/Method/Workflow/Task.pm
requires:
  Carp: 0
  Devel::Caller: 2.05
  Devel::Declare::Parser::Fennec: 0.004
  Exodist::Util: 0.007
  Exporter::Declare: 0.102
  Try::Tiny: 0
  perl: 5.008
resources:
  bugtracker: http://github.com/exodist/Method-Workflow/issues
  homepage: http://open-exodus.net/projects/Method-Workflow
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Method-Workflow
version: 0.204
